"""
Tone merging logic for the GenreNormalizerAgent.

This code takes the genre and tone resolutions produced by the resolver logic (resolver.py) and produces
a prioritized tone profile, effective tone, and records any conflicts between tones.

Conflict example would be if the user requested 'optimistic dystopian romance' because 'optimstic' and
'dystopian' will generally conflict in tone.
"""

from __future__ import annotations

from dataclasses import dataclass, field

from storymesh.schemas.genre_normalizer import GenreResolution, ToneResolution

_FALLBACK_TONE = "neutral" # A placeholder if somehow no tones were generated by the resolver.

@dataclass(frozen=True)
class ToneMergeResult:
    """
    The result of merging tones that are implicit from genres with tones that are requested by the user.

    This is an intra-agent data class and not a contract.
    """

    default_tones: list[str] = field(default_factory=list)
    explicit_tones: list[str] = field(default_factory=list)
    tone_profile: list[str] = field(default_factory=list)
    effective_tone: str = _FALLBACK_TONE # Ensure the effective tone is valid even if no tones were resolved
    tone_conflicts: list[str] | None = None

def _deduplicate_preserve_order(items: list[str]) -> list[str]:
    """Remove duplicates from a list without disrupting overall order."""
    seen: set[str] = set()
    result: list[str] = []
    
    for item in items:
        if item not in seen:
            seen.add(item)
            result.append(item)
    
    return result

def merge_tones(
        genre_resolutions: list[GenreResolution],
        tone_resolutions: list[ToneResolution]
    ) -> ToneMergeResult:
    """
    Merge default tones resolved from genres with explicit tones provided by the user.
    
    Priority:
    1. Explicit tones in order of appearance.
    2. Genre default tones ordered by resolution position.

    Args:
        genre_resolutions: Genre resolutions list that contains default_tones.
        tone_resolutions: Tone resolution list containing explicit normalized_tones.

    Returns:
        A ToneMergeResult with the full tone profile, effective tone, and a list of tone conflicts.
    """

    raw_defaults: list[str] = []
    for genre_resolution in genre_resolutions:
        raw_defaults.extend(genre_resolution.default_tones)
    default_tones = _deduplicate_preserve_order(raw_defaults)

    raw_explicits: list[str] = []
    for tone_resolution in tone_resolutions:
        raw_explicits.extend(tone_resolution.normalized_tones)
    explicit_tones = _deduplicate_preserve_order(raw_explicits)

    profile = list(explicit_tones)
    explicit_set = set(explicit_tones)
    for tone in default_tones:
        if tone not in explicit_set:
            profile.append(tone)

    if not profile:
        profile = [_FALLBACK_TONE]

    effective_tone = profile[0]

    # Detect conflicts
    tone_conflicts: list[str] | None = None
    if explicit_tones and default_tones:
        default_set = set(default_tones)
        conflicts = [
            f"explicit '{tone}' overrides genre default(s) "
            f"{sorted(default_set)}"
            for tone in explicit_tones
            if tone not in default_set
        ]
        if conflicts:
            tone_conflicts = conflicts

    return ToneMergeResult(
        default_tones = default_tones,
        explicit_tones = explicit_tones,
        tone_profile = profile,
        effective_tone = effective_tone,
        tone_conflicts = tone_conflicts
    )