"""
Tone merging logic for the GenreNormalizerAgent.

This code takes the genre and tone resolutions produced by the resolver logic (resolver.py) and produces
a prioritized tone profile, effective tone, and records any conflicts between tones.

Conflict example would be if the user requested 'optimistic dystopian romance' because 'optimstic' and
'dystopian' will generally conflict in tone.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any

from storymesh.schemas.genre_normalizer import GenreResolution, ToneResolution

_FALLBACK_TONE = "neutral" # A placeholder if somehow no tones were generated by the resolver.

@dataclass(frozen=True)
class ToneMergeResult:
    """
    The result of merging tones that are implicit from genres with tones that are requested by the user.

    This is an intra-agent data class and not a contract.
    Contract fields (user_tones, tone_override, override_note) travel downstream.
    The debug dict holds resolution details for observability.
    """

    # --- Downstream contract fields ---
    user_tones: list[str] = field(default_factory=list)
    tone_override: bool = False
    override_note: str | None = None

    # --- Debug/audit fields ---
    debug: dict[str, Any] = field(default_factory=dict)

def _deduplicate_preserve_order(items: list[str]) -> list[str]:
    """Remove duplicates from a list without disrupting overall order."""
    seen: set[str] = set()
    result: list[str] = []
    
    for item in items:
        if item not in seen:
            seen.add(item)
            result.append(item)
    
    return result

def merge_tones(
        genre_resolutions: list[GenreResolution],
        tone_resolutions: list[ToneResolution]
    ) -> ToneMergeResult:
    """
    Merge default tones resolved from genres with explicit tones provided by the user.

    Produces a simplified result for the downstream contract and detailed
    audit information in the debug dict.

    Args:
        genre_resolutions: Genre resolutions list that contains default_tones.
        tone_resolutions: Tone resolution list containing explicit normalized_tones.

    Returns:
        A ToneMergeResult with user_tones, tone_override, override_note, and debug data.
    """

    # --- Gather defaults from genres ---
    raw_defaults: list[str] = []
    for genre_resolution in genre_resolutions:
        raw_defaults.extend(genre_resolution.default_tones)
    default_tones = _deduplicate_preserve_order(raw_defaults)

    # --- Gather expanded explicit tones (for debug) ---
    raw_explicits: list[str] = []
    for tone_resolution in tone_resolutions:
        raw_explicits.extend(tone_resolution.normalized_tones)
    explicit_tones = _deduplicate_preserve_order(raw_explicits)

    # --- Extract user's original tone words (for contract) ---
    user_tones = _deduplicate_preserve_order([
        tone_resolution.input_token
        for tone_resolution in tone_resolutions
    ])

    # --- Build the full tone profile (for debug) ---
    profile = list(explicit_tones)
    explicit_set = set(explicit_tones)
    for tone in default_tones:
        if tone not in explicit_set:
            profile.append(tone)

    if not profile:
        profile = [_FALLBACK_TONE]

    effective_tone = profile[0]

    # --- Detect conflicts / override ---
    tone_conflicts: list[str] | None = None
    tone_override = False
    override_note: str | None = None

    if explicit_tones and default_tones:
        default_set = set(default_tones)
        conflicts = [
            f"explicit '{tone}' overrides genre default(s) "
            f"{sorted(default_set)}"
            for tone in explicit_tones
            if tone not in default_set
        ]
        if conflicts:
            tone_conflicts = conflicts
            tone_override = True
            user_str = ", ".join(user_tones)
            default_str = ", ".join(default_tones)
            override_note = (
                f"User tones ({user_str}) override typical "
                f"genre defaults ({default_str})"
            )

    # --- Assemble debug dict ---
    debug: dict[str, Any] = {
        "default_tones": default_tones,
        "explicit_tones": explicit_tones,
        "expanded_tones": explicit_tones,
        "tone_profile": profile,
        "effective_tone": effective_tone,
        "tone_conflicts": tone_conflicts,
    }

    return ToneMergeResult(
        user_tones = user_tones,
        tone_override = tone_override,
        override_note = override_note,
        debug = debug,
    )