GENRE_NORMALIZER_AGENT_VERSION = "1.0"
BOOK_FETCHER_AGENT_VERSION = "1.0"
BOOK_RANKER_AGENT_VERSION = "1.0"
THEME_EXTRACTOR_AGENT_VERSION = "1.0"
PROPOSAL_DRAFT_AGENT_VERSION = "1.1"
RUBRIC_JUDGE_AGENT_VERSION = "1.0"

AGENT_VERSIONS: dict[str, str] = {
    "Genre Normalizer": GENRE_NORMALIZER_AGENT_VERSION,
    "Book Fetcher": BOOK_FETCHER_AGENT_VERSION,
    "Book Ranker": BOOK_RANKER_AGENT_VERSION,
    "Theme Extractor": THEME_EXTRACTOR_AGENT_VERSION,
    "Proposal Draft": PROPOSAL_DRAFT_AGENT_VERSION,
    "Rubric Judge": RUBRIC_JUDGE_AGENT_VERSION,
}