GENRE_NORMALIZER_AGENT_VERSION = "1.0"
BOOK_FETCHER_AGENT_VERSION = "1.0"
BOOK_RANKER_AGENT_VERSION = "1.0"
THEME_EXTRACTOR_AGENT_VERSION = "1.0"
PROPOSAL_DRAFT_AGENT_VERSION = "1.2"
PROPOSAL_READER_AGENT_VERSION = "1.0"
RUBRIC_JUDGE_AGENT_VERSION = "1.0"
COVER_ART_AGENT_VERSION = "1.0"
STORY_WRITER_AGENT_VERSION = "1.0"
BOOK_ASSEMBLER_AGENT_VERSION = "1.0"
RESONANCE_REVIEWER_AGENT_VERSION = "1.0"

AGENT_VERSIONS: dict[str, str] = {
    "Genre Normalizer": GENRE_NORMALIZER_AGENT_VERSION,
    "Book Fetcher": BOOK_FETCHER_AGENT_VERSION,
    "Book Ranker": BOOK_RANKER_AGENT_VERSION,
    "Theme Extractor": THEME_EXTRACTOR_AGENT_VERSION,
    "Proposal Draft": PROPOSAL_DRAFT_AGENT_VERSION,
    "Proposal Reader": PROPOSAL_READER_AGENT_VERSION,
    "Rubric Judge": RUBRIC_JUDGE_AGENT_VERSION,
    "Cover Art": COVER_ART_AGENT_VERSION,
    "Story Writer": STORY_WRITER_AGENT_VERSION,
    "Book Assembler": BOOK_ASSEMBLER_AGENT_VERSION,
    "Resonance Reviewer": RESONANCE_REVIEWER_AGENT_VERSION,
}