GENRE_CONSTRAINT_SCHEMA_VERSION = "1.0"
PROPOSAL_SCHEMA_VERSION = "1.0"
THEMEPACK_SCHEMA_VERSION = "1.0"

SCHEMA_VERSIONS: dict[str, str] = {
    "Genre Constraint": GENRE_CONSTRAINT_SCHEMA_VERSION,
    "Proposal": PROPOSAL_SCHEMA_VERSION,
    "Themepack": THEMEPACK_SCHEMA_VERSION,
}