"""Email delivery module for StoryMesh.

Provides rich HTML email construction and SMTP delivery for generated books.
When a recipient is configured (via ``storymesh.config.yaml`` or a per-run
CLI override), the book assembler node calls :func:`deliver_book` after the
PDF and EPUB have been written to disk.

MIME structure with cover image::

    MIMEMultipart('mixed')
    ├── MIMEMultipart('related')
    │   ├── MIMEMultipart('alternative')
    │   │   ├── MIMEText  (plain-text fallback)
    │   │   └── MIMEText  (HTML body referencing cid:cover_art)
    │   └── MIMEImage     (cover PNG, Content-ID: cover_art)
    ├── MIMEBase          (PDF attachment)
    └── MIMEBase          (EPUB attachment, when include_epub=True)

Without a cover image the ``related`` wrapper is omitted and
``alternative`` sits directly inside ``mixed``.
"""

from __future__ import annotations

import logging
import os
import re
import smtplib
from dataclasses import dataclass
from email import encoders
from email.mime.base import MIMEBase
from email.mime.image import MIMEImage
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from pathlib import Path
from typing import Any

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# HTML / plain-text templates
# ---------------------------------------------------------------------------

_HTML_TEMPLATE = """\
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{title}</title>
</head>
<body style="margin:0;padding:0;background-color:#f4f1eb;font-family:Georgia,'Times New Roman',serif;">
  <table width="100%" cellpadding="0" cellspacing="0" border="0"
         style="background-color:#f4f1eb;">
    <tr>
      <td align="center" style="padding:32px 16px;">

        <!-- Card wrapper -->
        <table width="600" cellpadding="0" cellspacing="0" border="0"
               style="max-width:600px;background-color:#ffffff;
                      border-radius:6px;
                      box-shadow:0 4px 24px rgba(0,0,0,0.10);">

          <!-- Cover image header -->
          <tr>
            <td align="center"
                style="background-color:#1a1a2e;border-radius:6px 6px 0 0;
                       padding:40px 40px 32px;">
              {cover_section}
            </td>
          </tr>

          <!-- Title -->
          <tr>
            <td align="center"
                style="padding:36px 48px 8px;">
              <h1 style="margin:0;font-size:26px;font-weight:normal;
                         letter-spacing:0.04em;color:#1a1a2e;
                         font-family:Georgia,'Times New Roman',serif;">
                {title}
              </h1>
            </td>
          </tr>

          <!-- Divider -->
          <tr>
            <td style="padding:16px 48px 0;">
              <hr style="border:none;border-top:1px solid #d9d3c7;margin:0;">
            </td>
          </tr>

          <!-- Synopsis -->
          <tr>
            <td style="padding:28px 48px 32px;font-size:15px;line-height:1.75;
                       color:#2c2c2c;font-family:Georgia,'Times New Roman',serif;">
              {synopsis_html}
            </td>
          </tr>

          <!-- Divider -->
          <tr>
            <td style="padding:0 48px;">
              <hr style="border:none;border-top:1px solid #d9d3c7;margin:0;">
            </td>
          </tr>

          <!-- Footer -->
          <tr>
            <td align="center"
                style="padding:20px 48px 28px;font-size:12px;color:#888888;
                       font-family:Arial,Helvetica,sans-serif;">
              Generated by <strong style="color:#555555;">StoryMesh</strong>
              &nbsp;&middot;&nbsp;
              {attachment_note}
            </td>
          </tr>

        </table>
      </td>
    </tr>
  </table>
</body>
</html>
"""

_COVER_WITH_IMAGE = (
    '<img src="cid:cover_art" alt="{title}" '
    'style="max-width:240px;border-radius:4px;'
    'box-shadow:0 8px 32px rgba(0,0,0,0.55);">'
)

_COVER_TYPOGRAPHIC = """\
<p style="margin:0;font-size:36px;font-weight:bold;color:#ffffff;
          letter-spacing:0.06em;font-family:Georgia,'Times New Roman',serif;">
  {title}
</p>
"""


# ---------------------------------------------------------------------------
# Configuration dataclass
# ---------------------------------------------------------------------------

@dataclass
class EmailConfig:
    """Resolved email delivery configuration.

    Credentials are sourced from environment variables
    (``STORYMESH_SMTP_USER``, ``STORYMESH_SMTP_PASSWORD``) with
    fallback to the values in ``storymesh.config.yaml``.
    """

    smtp_host: str
    smtp_port: int
    smtp_user: str
    smtp_password: str
    from_address: str
    recipient: str
    include_epub: bool

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> EmailConfig:
        """Construct an :class:`EmailConfig` from a config section dict.

        Environment variables ``STORYMESH_SMTP_USER`` and
        ``STORYMESH_SMTP_PASSWORD`` override config-file values when set.

        Args:
            data: The ``email`` section of the merged storymesh config.

        Returns:
            A fully resolved :class:`EmailConfig`.
        """
        smtp_user = (
            os.environ.get("STORYMESH_SMTP_USER")
            or str(data.get("smtp_user", ""))
        )
        smtp_password = (
            os.environ.get("STORYMESH_SMTP_PASSWORD")
            or str(data.get("smtp_password", ""))
        )
        return cls(
            smtp_host=str(data.get("smtp_host", "")),
            smtp_port=int(data.get("smtp_port", 587)),
            smtp_user=smtp_user,
            smtp_password=smtp_password,
            from_address=str(data.get("from_address", "")),
            recipient=str(data.get("recipient", "")),
            include_epub=bool(data.get("include_epub", False)),
        )

    @property
    def effective_from(self) -> str:
        """Effective sender address — ``from_address`` or ``smtp_user``."""
        return self.from_address or self.smtp_user

    @property
    def is_configured(self) -> bool:
        """Return True when the minimum fields required to send are present."""
        return bool(self.smtp_host and self.smtp_user and self.smtp_password)


# ---------------------------------------------------------------------------
# Filename helper
# ---------------------------------------------------------------------------

def title_to_filename(title: str) -> str:
    """Convert a story title to a ``Title_Case_Snake`` filename stem.

    Non-alphanumeric, non-space characters are stripped, words are split on
    whitespace, and rejoined with underscores.  The original word casing is
    preserved.

    Examples::

        >>> title_to_filename("The Dragon's Lair")
        'The_Dragons_Lair'
        >>> title_to_filename("Iron & Blood: A Story")
        'Iron_Blood_A_Story'
        >>> title_to_filename("  Whitespace   ")
        'Whitespace'

    Args:
        title: Raw story title string.

    Returns:
        Filename stem suitable for use as ``{stem}.pdf`` etc.
    """
    cleaned = re.sub(r"[^\w\s]", "", title, flags=re.UNICODE)
    parts = cleaned.split()
    return "_".join(parts) if parts else "Untitled"


# ---------------------------------------------------------------------------
# Email construction
# ---------------------------------------------------------------------------

def _synopsis_to_html(synopsis: str) -> str:
    """Wrap each non-empty paragraph of *synopsis* in ``<p>`` tags."""
    paragraphs = [p.strip() for p in synopsis.strip().splitlines() if p.strip()]
    return "".join(
        f'<p style="margin:0 0 14px 0;">{p}</p>' for p in paragraphs
    )


def build_html_email(
    *,
    title: str,
    synopsis: str,
    cover_image_bytes: bytes | None,
    pdf_path: str,
    epub_path: str,
    include_epub: bool,
    from_address: str,
    recipient: str,
    filename_stem: str,
) -> MIMEMultipart:
    """Construct a multipart MIME email with rich HTML body and book attachments.

    Args:
        title: Story title, used in the email subject and HTML heading.
        synopsis: Back-cover synopsis text; newlines are converted to paragraphs.
        cover_image_bytes: Raw PNG bytes of the cover image, or ``None`` for a
            typographic fallback header.
        pdf_path: Absolute path to the PDF file on disk.
        epub_path: Absolute path to the EPUB file on disk, or empty string.
        include_epub: When True, attach the EPUB alongside the PDF.
        from_address: Sender address for the ``From`` header.
        recipient: Recipient address for the ``To`` header.
        filename_stem: Base filename without extension (e.g. ``The_Dragons_Lair``).

    Returns:
        A fully assembled :class:`email.mime.multipart.MIMEMultipart` ready
        to pass to :func:`send_email`.
    """
    # -- Attachment note shown in footer --
    attachments: list[str] = []
    if pdf_path:
        attachments.append(f"{filename_stem}.pdf")
    if include_epub and epub_path:
        attachments.append(f"{filename_stem}.epub")
    attachment_note = (
        "Attached: " + " &amp; ".join(attachments) if attachments else ""
    )

    # -- Cover section HTML --
    if cover_image_bytes:
        cover_section = _COVER_WITH_IMAGE.format(title=title)
    else:
        cover_section = _COVER_TYPOGRAPHIC.format(title=title)

    # -- HTML body --
    html_body = _HTML_TEMPLATE.format(
        title=title,
        cover_section=cover_section,
        synopsis_html=_synopsis_to_html(synopsis),
        attachment_note=attachment_note,
    )

    # -- Plain-text fallback --
    plain_body = (
        f"{title}\n"
        f"{'=' * len(title)}\n\n"
        f"{synopsis.strip()}\n\n"
        f"--\nGenerated by StoryMesh\n"
    )
    if attachments:
        plain_body += f"Attached: {', '.join(attachments)}\n"

    # -- Assemble MIME tree --
    outer = MIMEMultipart("mixed")
    outer["Subject"] = f"Your StoryMesh Story: {title}"
    outer["From"] = from_address
    outer["To"] = recipient

    alternative = MIMEMultipart("alternative")
    alternative.attach(MIMEText(plain_body, "plain", "utf-8"))
    alternative.attach(MIMEText(html_body, "html", "utf-8"))

    if cover_image_bytes:
        related = MIMEMultipart("related")
        related.attach(alternative)
        cover_img = MIMEImage(cover_image_bytes, _subtype="png")
        cover_img.add_header("Content-ID", "<cover_art>")
        cover_img.add_header(
            "Content-Disposition", "inline", filename="cover_art.png"
        )
        related.attach(cover_img)
        outer.attach(related)
    else:
        outer.attach(alternative)

    # -- PDF attachment --
    if pdf_path:
        _attach_file(outer, pdf_path, f"{filename_stem}.pdf", "application/pdf")

    # -- EPUB attachment (conditional) --
    if include_epub and epub_path:
        _attach_file(
            outer,
            epub_path,
            f"{filename_stem}.epub",
            "application/epub+zip",
        )

    return outer


def _attach_file(
    message: MIMEMultipart,
    file_path: str,
    filename: str,
    mime_type: str,
) -> None:
    """Read *file_path* from disk and attach it to *message*.

    Args:
        message: The outer MIME container to attach to.
        file_path: Absolute path to the file.
        filename: Filename shown in the email client attachment list.
        mime_type: Full MIME type string (e.g. ``"application/pdf"``).
    """
    main_type, sub_type = mime_type.split("/", 1)
    part = MIMEBase(main_type, sub_type)
    part.set_payload(Path(file_path).read_bytes())
    encoders.encode_base64(part)
    part.add_header("Content-Disposition", "attachment", filename=filename)
    message.attach(part)


# ---------------------------------------------------------------------------
# SMTP delivery
# ---------------------------------------------------------------------------

def send_email(
    *,
    config: EmailConfig,
    message: MIMEMultipart,
    recipient: str,
) -> None:
    """Send *message* via STARTTLS SMTP using the provided configuration.

    Args:
        config: Resolved :class:`EmailConfig` with SMTP credentials.
        message: Fully assembled MIME message.
        recipient: Delivery address (may differ from ``To`` header for BCC
            scenarios, but is typically the same).

    Raises:
        smtplib.SMTPException: On any SMTP-level error.
        OSError: If the SMTP host is unreachable.
    """
    logger.debug(
        "Connecting to SMTP %s:%d as %s",
        config.smtp_host,
        config.smtp_port,
        config.smtp_user,
    )
    with smtplib.SMTP(config.smtp_host, config.smtp_port) as smtp:
        smtp.ehlo()
        smtp.starttls()
        smtp.ehlo()
        smtp.login(config.smtp_user, config.smtp_password)
        smtp.sendmail(config.effective_from, recipient, message.as_string())

    logger.info("Email delivered to %s", recipient)


# ---------------------------------------------------------------------------
# High-level entry point
# ---------------------------------------------------------------------------

def deliver_book(
    *,
    title: str,
    synopsis: str,
    cover_image_bytes: bytes | None,
    pdf_path: str,
    epub_path: str,
    recipient: str,
    email_config: EmailConfig,
) -> None:
    """Build and send a rich HTML email with the generated book attached.

    This is the primary entry point called by the book assembler node.
    All validation of ``email_config`` completeness is performed here before
    attempting delivery so that misconfiguration produces a clear log error
    rather than a pipeline crash.

    Args:
        title: Story title.
        synopsis: Back-cover synopsis (plain text).
        cover_image_bytes: Cover image PNG bytes, or ``None``.
        pdf_path: Absolute path to the PDF on disk.
        epub_path: Absolute path to the EPUB on disk, or empty string.
        recipient: Delivery email address.
        email_config: Resolved SMTP and delivery settings.
    """
    if not recipient:
        logger.warning("deliver_book called with empty recipient — skipping.")
        return

    if not email_config.is_configured:
        logger.error(
            "Email delivery is requested but SMTP is not fully configured "
            "(smtp_host, smtp_user, and smtp_password are all required). "
            "Set them in storymesh.config.yaml or via STORYMESH_SMTP_USER / "
            "STORYMESH_SMTP_PASSWORD environment variables."
        )
        return

    filename_stem = title_to_filename(title)
    message = build_html_email(
        title=title,
        synopsis=synopsis,
        cover_image_bytes=cover_image_bytes,
        pdf_path=pdf_path,
        epub_path=epub_path,
        include_epub=email_config.include_epub,
        from_address=email_config.effective_from,
        recipient=recipient,
        filename_stem=filename_stem,
    )

    try:
        send_email(config=email_config, message=message, recipient=recipient)
    except (OSError, smtplib.SMTPException) as exc:
        logger.error("Email delivery failed: %s", exc)
